description:
  ・EDSR(num_residual_blocks=8)
  ・1000epochs
  
dataset_dir: ./datasets/df2k_no_person
batch_size: 4
num_workers: 2
epochs: 1000
output_dir: ./outputs/240826_02
lr: 0.0005
scheduler:
  t_initial: 500
  lr_min: 0.000005
  warmup_t: 10
  warmup_lr_init: 0.000005
  warmup_prefix: True