description:
  ・convを追加
  
dataset_dir: ./datasets/raw
batch_size: 4
num_workers: 2
epochs: 100
output_dir: ./outputs/240820_01
lr: 0.003
scheduler:
  t_initial: 100
  lr_min: 0.00003
  warmup_t: 10
  warmup_lr_init: 0.00003
  warmup_prefix: True
