description:
  ・1000epochs

dataset_dir: ./datasets/raw
batch_size: 4
num_workers: 2
epochs: 1000
output_dir: ./outputs/240817_07
lr: 0.003
scheduler:
  t_initial: 100
  lr_min: 0.00003
  warmup_t: 10
  warmup_lr_init: 0.00003
  warmup_prefix: True
