description:
  ・EDSR(num_residual_blocks=8)
  ・CutMix
  ・df2k_no_person
  
dataset_dir: ./datasets/df2k_no_person
batch_size: 4
num_workers: 2
epochs: 100
output_dir: ./outputs/240823_04
lr: 0.0005
scheduler:
  t_initial: 100
  lr_min: 0.000005
  warmup_t: 10
  warmup_lr_init: 0.000005
  warmup_prefix: True
