description:
  ・EDSR(num_residual_blocks=8)
  ・500epochs
  ・L1Loss
  
dataset_dir: ./datasets/df2k_no_person
batch_size: 4
num_workers: 2
epochs: 500
output_dir: ./outputs/240830_01
lr: 0.0005
scheduler:
  t_initial: 500
  lr_min: 0.000005
  warmup_t: 10
  warmup_lr_init: 0.000005
  warmup_prefix: True