description:
  ・PixelShuffleを2回に
  ・240817_04のモデルで推論。反転した4枚に対して推論して、合成する

dataset_dir: ./datasets/raw
# batch_size: 4
# num_workers: 2
# epochs: 500
output_dir: ./outputs/240817_05
# lr: 0.003
# scheduler:
#   lr_min: 0.00003
