description:
  ・EDWSR、channel=64、num_residual_blocks=9
  
dataset_dir: ./datasets/df2k_no_person
batch_size: 4
num_workers: 2
epochs: 600
output_dir: ./outputs/240827_06
lr: 0.0005
scheduler:
  t_initial: 600
  lr_min: 0.000005
  warmup_t: 10
  warmup_lr_init: 0.000005
  warmup_prefix: True
