description:
  ・EDSR(num_residual_blocks=8)
  ・200epochs

dataset_dir: ./datasets/df2k_no_person
batch_size: 4
num_workers: 2
epochs: 200
output_dir: ./outputs/240823_06_02
lr: 0.0003
scheduler:
  t_initial: 200
  lr_min: 0.000003
  warmup_t: 10
  warmup_lr_init: 0.000003
  warmup_prefix: True
