description:
  ・PixelShuffleを2回に

dataset_dir: ./datasets/raw
batch_size: 4
num_workers: 2
epochs: 100
output_dir: ./outputs/240817_03
lr: 0.003
scheduler:
  lr_min: 0.00003
  warmup_t: 10
  warmup_lr_init: 0.00003
  warmup_prefix: True
