description:
  This is a sample configuration file for the project.

dataset_dir: ./datasets/sample
batch_size: 4
num_workers: 2
epochs: 100
output_dir: ./outputs/sample
lr: 0.0005
scheduler:
  t_initial: 100
  lr_min: 0.000005
  warmup_t: 10
  warmup_lr_init: 0.000005
  warmup_prefix: True
